package inter;



import java.awt.PopupMenu;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ragragui
 */
public class authentification extends javax.swing.JFrame {

 
    public authentification() {
        
        initComponents();   
    }
   



/**
     * Creates new form NewJFrame
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnLog = new javax.swing.JButton();
        home = new javax.swing.JLabel();
        jtfPassword = new javax.swing.JPasswordField();
        jl2 = new javax.swing.JLabel();
        jtfLogin = new javax.swing.JTextField();
        jl1 = new javax.swing.JLabel();
        titre1 = new javax.swing.JLabel();
        titre2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jbtnLog.setBackground(new java.awt.Color(255, 153, 153));
        jbtnLog.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        jbtnLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginoutline_110706.png"))); // NOI18N
        jbtnLog.setText("Log In");
        jbtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLog);
        jbtnLog.setBounds(400, 260, 130, 40);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_icon_176905 (1).png"))); // NOI18N
        jPanel1.add(home);
        home.setBounds(10, 80, 250, 210);

        jtfPassword.setFont(new java.awt.Font("Source Code Pro Black", 1, 14)); // NOI18N
        jtfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jtfPassword);
        jtfPassword.setBounds(380, 180, 190, 30);

        jl2.setBackground(new java.awt.Color(35, 151, 242));
        jl2.setFont(new java.awt.Font("Source Code Pro Black", 1, 14)); // NOI18N
        jl2.setText("Password");
        jPanel1.add(jl2);
        jl2.setBounds(290, 180, 80, 30);

        jtfLogin.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jtfLogin.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jtfLogin);
        jtfLogin.setBounds(380, 110, 190, 30);

        jl1.setBackground(new java.awt.Color(35, 151, 242));
        jl1.setFont(new java.awt.Font("Source Code Pro Black", 1, 14)); // NOI18N
        jl1.setText("Login");
        jPanel1.add(jl1);
        jl1.setBounds(310, 100, 70, 40);

        titre1.setFont(new java.awt.Font("Source Code Pro Black", 1, 40)); // NOI18N
        titre1.setForeground(new java.awt.Color(255, 153, 153));
        titre1.setText("Authenti");
        jPanel1.add(titre1);
        titre1.setBounds(100, 0, 180, 52);

        titre2.setFont(new java.awt.Font("Source Code Pro Black", 1, 40)); // NOI18N
        titre2.setText("fication");
        jPanel1.add(titre2);
        titre2.setBounds(280, 0, 240, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fond.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 0, 310, 310);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 10, 73, 23);

        background.setBackground(new java.awt.Color(255, 204, 204));
        background.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e87f33e3b3df211ff25947cbd31e2d17.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 270, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      public static int nbrTentative=3;
    private void jbtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogActionPerformed
        // TODO add your handling code here:
        
        
       boolean r=false;
       r=Compte_1.isAuthentificated(jtfLogin.getText(), jtfPassword.getText());
       if(r){
           this.setVisible(false);
           
       }else{
           JOptionPane jp= new JOptionPane();
           JFrame j= new JFrame();
           jp.showMessageDialog(j,"INCORRECT ! vous devez essayer l'username ou le mot de passe sinon votre Compte est désactivé ");}
            
              
       
    
    
            
        
        
        
    }//GEN-LAST:event_jbtnLogActionPerformed

    private void jtfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Page1 p=new Page1();
        p.setVisible(true);
        this.setVisible(false);
           
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
      
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new authentification().setVisible(true);
   }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnLog;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    public static javax.swing.JTextField jtfLogin;
    private javax.swing.JPasswordField jtfPassword;
    private javax.swing.JLabel titre1;
    private javax.swing.JLabel titre2;
    // End of variables declaration//GEN-END:variables
}
